version: '3.2'

services:
  web:
    build:
      context: .
      cache_from:
        - ${DOCKER_REGISTRY_HOST}/${DOCKER_IMAGE}:${BRANCH_TAG}
      args:
        - BUILD_ENV=production
        - RUBY_ENV=production
        - NODE_ENV=production
        - ASSET_HOST
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_IMAGE}:${BRANCH_TAG}
    container_name: nimble_devops_ic_web_web
    command: bin/start.sh
    ports:
      - "${PORT}:${PORT}"
    stdin_open: true
    tty: true
    volumes:
      - "ruby-bundle:/bundle"
    environment:
      - RACK_ENV=production
      - RAILS_ENV=production
      - NODE_ENV=production
      - ASSET_HOST
      - DEFAULT_HOST
      - MAILER_SENDER
      - RAILS_MASTER_KEY

volumes:
  ruby-bundle:
